services:
  - type: web
    name: scribe-backend
    env: docker
    region: singapore
    plan: free 
    dockerfilePath: ./backend/Dockerfile
    rootDir: ./backend
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: scribe-db
          property: connectionString

databases:
  - name: scribe-db
    databaseName: scribe
    user: scribe
    plan: starter